### ISSUE TITLE
Cmactions fix

### ISSUE THREAD

**Issue by Theitfixer85** [OpensourceCedric/android_device_motorola_cedric-fix#3]
Your cmactions doesn't compile due to syntax errors 

There is a much better solution - use the original cmactions from Wzedlare device tree

Now git clone this into vendor/cmsdk 
https://github.com/AICP/vendor_cmsdk

**Comment by ATechnoHazard** [comment]
Cmactions most certainly works, this tree has been used for XOSP and Glazed rom builds. Do not use this tree on Lineage based roms, it is only for aosp-caf. Wzedlare tree gives build error for aosp-caf due to missing FileUtils.java, therefore this temp fix was implemented. No need to clone the full cmsdk.
